apply plugin: "com.liferay.defaults.plugin"
apply plugin: "com.liferay.plugin"

FileTree tldFileTree = fileTree(projectDir) {
	exclude "**/bin/**"
	exclude "**/build/**"
	exclude "**/classes/**"
	exclude "**/sdk/**"
	exclude "**/test/**"
	include "**/liferay-*.tld"
}

task tlddoc(type: JavaExec)
task validateTld
task zipTlddoc(type: Jar)

artifacts {
	if (!tldFileTree.isEmpty()) {
		archives zipTlddoc
	}
}

configurations {
	tlddocConf
}

dependencies {
	tlddocConf group: "taglibrarydoc", name: "tlddoc", version: "1.3"
}

tlddoc {
	File docTaglibsDir = new File(project.docsDir, "tlddoc")

	args = _getTlddocArgsList(docTaglibsDir, tldFileTree)

	classpath = configurations.tlddocConf

	dependsOn validateTld

	docTaglibsDir.mkdirs()

	jvmArgs "-Xmx256m"

	main = "com.sun.tlddoc.TLDDoc"

	outputs.dir(docTaglibsDir)
}

validateTld {
	ant {
		schemavalidate {
			tldFileTree.addToAntBuilder(ant, "fileset", FileCollection.AntType.FileSet)
		}
	}
}

zipJavadoc {
	extension = "jar"
}

zipTlddoc {
	classifier = "tlddoc"

	dependsOn tlddoc

	from tlddoc.outputs
}

private ArrayList _getTlddocArgsList(File docTaglibsDir, FileTree tldFileTree) {
	ArrayList argsList = []

	argsList << "-d"
	argsList << docTaglibsDir

	tldFileTree.each {
		argsList << it.toString()
	}

	return argsList
}