/*subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

		tasks.withType(Jar) {
			destinationDir = file("${rootProject.buildDir}/archetypes")
		}

    repositories {
        mavenCentral()
    }

    publishing {
        repositories {
            maven {
                url "${rootProject.buildDir}/repo" // change to point to your repo, e.g. http://my.org/repo
            }
        }
    }
}

apply plugin: 'java'

dependencies {
	testCompile group: "junit", name: "junit", version: "4.12"
}

repositories {
	mavenLocal()
	mavenCentral()
}
*/

// sourceSets {
//     main {
//         resources {
//             exclude '**/pom.xml'
// 			exclude '**/META-INF'
//         }
//     }
// }
//
// project(":liferay-module-mvcportlet") {
// 	task archetypeJar(type: Jar) {
// 		from("../src/main/resources/standalone/mvcportlet") {
// 			exclude "build.gradle"
// 		}
// 		eachFile {file ->
// 			if (!file.path.startsWith('META-INF')) {
// 				file.path = 'archetype-resources/' + file.path
// 			}
// 		}
// 	}
//
//   publishing {
//     publications {
//       maven(MavenPublication) {
//         groupId 'com.liferay'
//         artifactId 'liferay-module-mvcportlet'
//         version '1.0.0'
// 		artifact archetypeJar
//       }
//     }
//   }
// }
//
// project(":liferay-module-portlet") {
// 		task archetypeJar(type: Jar) {
// 			from("../src/main/resources/standalone/portlet") {
// 				exclude "build.gradle"
// 			}
// 			eachFile {file ->
// 				if (!file.path.startsWith('META-INF')) {
// 					file.path = 'archetype-resources/' + file.path
// 				}
// 			}
// 		}
//     publishing {
//         publications {
//             maven(MavenPublication) {
//                 groupId 'com.liferay'
//                 artifactId 'liferay-module-portlet'
//                 version '1.0.0'
// 								artifact archetypeJar
//             }
//         }
//     }
// }

dependencies {
	compile project(":sdk:project-templates-mvcportlet")
	compile project(":sdk:project-templates-portlet")
}

ext {
	gradlePluginVersions = [
		"com.liferay.gradle.plugins": "1.0.369"
	]
}

processResources {
	filesMatching("**/build.gradle") {
		filter {
			String line ->

			gradlePluginVersions.each {
				String name, String version ->

				line = line.replace "group: \"com.liferay\", name: \"${name}\", version: \"latest.release\"", "group: \"com.liferay\", name: \"${name}\", version: \"${version}\""
			}

			return line
		}
	}

	rename "gitignore", ".gitignore"
}