dependencies {
	provided group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.2.0"
	provided group: "com.beust", name: "jcommander", version: "1.48"
	provided group: "org.apache.maven.archetype", name: "archetype-common", version: "2.4"
	provided project(":sdk:project-templates-mvcportlet")
	provided project(":sdk:project-templates-portlet")
	provided project(":sdk:project-templates-service")
}

bundle {
    includeTransitiveDependencies = true
}

ext {
	gradlePluginVersions = [
		"com.liferay.gradle.plugins": "1.0.369"
	]
}

processResources {
	filesMatching("**/build.gradle") {
		filter {
			String line ->

			gradlePluginVersions.each {
				String name, String version ->

				line = line.replace "group: \"com.liferay\", name: \"${name}\", version: \"latest.release\"", "group: \"com.liferay\", name: \"${name}\", version: \"${version}\""
			}

			return line
		}
	}

	rename "gitignore", ".gitignore"
}
